### ISSUE TITLE
大神，复数乘法用cublas库可不可以？

### ISSUE THREAD

**Issue by QuantumLiu** [zchlong/algorithms-cuda#1]
`cublasStatus_t cublasCgemm(cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, const cuComplex *alpha, const cuComplex *A, int lda, const cuComplex *B, int ldb, const cuComplex *beta, cuComplex *C, int ldc) 
cublasStatus_t cublasZgemm(cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, const cuDoubleComplex *alpha, const cuDoubleComplex *A, int lda, const cuDoubleComplex *B, int ldb, const cuDoubleComplex *beta, cuDoubleComplex *C, int ldc)

Read more at: http://docs.nvidia.com/cuda/cublas/index.html#ixzz4RSDve2LC 
Follow us: @GPUComputing on Twitter | NVIDIA on Facebook`

**Comment by DrZhang99** [comment]
cuBLAS我没有用过，不过从文档来看是可以的。在cuBLAS文档中：
* [2.5.4. cublas<t>axpy()](http://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-axpy)实现`y[j] = αx[k]+y[j]`， `x`,`y`,`α`都可以是复数。
* [2.6. cuBLAS Level-2 Function Reference](http://docs.nvidia.com/cuda/cublas/index.html#cublas-level-2-function-reference)是关于矩阵和向量的运算，如[2.6.1. cublas<t>gbmv()](http://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gbmv)就是关于矩阵和向量的乘法运算。
* [2.7. cuBLAS Level-3 Function Reference](http://docs.nvidia.com/cuda/cublas/index.html#cublas-level-3-function-reference) 是关于矩阵和矩阵的运算，如[2.7.1. cublas<t>gemm()](http://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemm)就是关于矩阵和矩阵的乘法运算。

上面的这些运算都有复数版本的API，可以参考[cuBLAS文档](http://docs.nvidia.com/cuda/cublas/index.html)。

**Comment by QuantumLiu** [comment]
我现在在想cnn的反向传播能不能也用fft
