### ISSUE TITLE
卷积

### ISSUE THREAD

**Issue by Riverhe2014** [zchlong/algorithms-cuda#2]
大神，请问你写的cuda版本是基于一维卷积运算的吗

**Comment by DrZhang99** [comment]
是一维卷积。可以参考 https://chaolongzhang.github.io/2016/algorithms-on-cuda-fft-convolution/

**Comment by Riverhe2014** [comment]
可以加我一下qq吗？我现在做二位卷积优化，可是开源的都不能打到我的要求，可以咨询一下你吗？我qq 247932449 谢谢，qq问题的答案是10

**Comment by SunlifeV** [comment]
> 
dalao, have you solved it now?

**Comment by SunlifeV** [comment]
> 可以加我一下qq吗？我现在做二位卷积优化，可是开源的都不能打到我的要求，可以咨询一下你吗？我qq 247932449 谢谢，qq问题的答案是10

dalao, have you solved it now?
